ServiceHost/Areas/Administration/Pages/Blog/ArticleCategories/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using BlogManagement.Application.Contracts.ArticleCategory;
using BlogManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Blog.ArticleCategories
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public ArticleCategorySearchModel SearchModel { get; set; }
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(ArticleCategorySearchModel searchModel)
        {
            ArticleCategories = _articleCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateArticleCategory();
            return Partial("./Create", command);
        }

        [NeedsPermission(BlogPermissions.CreateArticleCategory)]
        public IActionResult OnPostCreate(CreateArticleCategory command)
        {
            if(ModelState.IsValid)
            {
                var result = _articleCategoryApplication.Create(command);
                return new JsonResult(result);
            }
            return new JsonResult(false);
        }

        public IActionResult OnGetEdit(long id)
        {
            var command = _articleCategoryApplication.GetDetails(id);
            return Partial("./Edit", command);
        }

        [NeedsPermission(BlogPermissions.EditArticleCategory)]
        public IActionResult OnPostEdit(EditArticleCategory command)
        {
            if(ModelState.IsValid)
            {
                var result = _articleCategoryApplication.Edit(command);
                return new JsonResult(result);
            }
            return new JsonResult(false);
        }       
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }


        [BindProperty]
        public CreateArticle Article { get; set; }
        public SelectList ArticleCategories
        {
            get 
            {
                return new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
            }
        }

        public void OnGet()
        {
            Article = new CreateArticle();
            //ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle article)
        {
            if (ModelState.IsValid)
            {
                var result = _articleApplication.Create(article);
                return RedirectToPage("./Index");
            }
            return Page();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [BindProperty]
        public EditArticle Article { get; set; }
        
        public SelectList ArticleCategories
        {
            get
            {
                return new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
            }
        }

        
        public void OnGet(long id)
        {
            Article = _articleApplication.GetDetails(id);
            //ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name", Article?.CategoryId);
        }

        public IActionResult OnPost(EditArticle article)
        {
            if (ModelState.IsValid)
            {
                var result = _articleApplication.Edit(article);
                return RedirectToPage("./Index");
            }
            return Page();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Index.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public ArticleSearchModel SearchModel { get; set; }
        public List<ArticleViewModel> Articles { get; set; }
        public SelectList ArticleCategories { get; set; }


        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(ArticleSearchModel searchModel)
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
            Articles = _articleApplication.Search(searchModel);
        }

        public IActionResult OnGetRemove(long id)
        {
            var result = _articleApplication.Remove(id);
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetRestore(long id)
        {
            var result = _articleApplication.Restore(id);
            return RedirectToPage("./Index");

        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        public List<ProductCategoryViewModel> ProductCategories { get; set; }
        public ProductCategorySearchModel SearchModel { get; set; }

        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }

        [NeedsPermission(ShopPermissions.ListProductCategories)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public IActionResult OnPostCreate(CreateProductCategory command)
        {
            if(ModelState.IsValid)
            {
                var result = _productCategoryApplication.Create(command);
                return new JsonResult(result);
            }
            return new JsonResult(false);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("./Edit", productCategory);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public JsonResult OnPostEdit(EditProductCategory command)
        {
            if (ModelState.IsValid)
            {
                var result = _productCategoryApplication.Edit(command);
                return new JsonResult(result);
            }
            return new JsonResult(false);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Shop/Products/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Infrastructure.Configuration.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.Products
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<ProductViewModel> Products { get; set; }
        public ProductSearchModel SearchModel { get; set; }
        public SelectList ProductCategories { get; set; }

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
        }

        [NeedsPermission(ShopPermissions.ListProducts)]
        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Products = _productApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProduct()
            {
                Categories = _productCategoryApplication.GetProductCategories()
            };
            return Partial("./Create", command);
        }

        [NeedsPermission(ShopPermissions.CreateProduct)]
        public IActionResult OnPostCreate(CreateProduct command)
        {
            var result = _productApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var product = _productApplication.GetDetails(id);
            product.Categories = _productCategoryApplication.GetProductCategories();
            return Partial("./Edit", product);
        }

        [NeedsPermission(ShopPermissions.EditProduct)]
        public JsonResult OnPostEdit(EditProduct command)
        {
            var result = _productApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Article.cshtml.cs
using _01_LampshadeQuery;
using _01_LampshadeQuery.Contracts.Article;
using _01_LampshadeQuery.Contracts.ArticleCategory;
using CommentManagement.Application.Contracts.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Pages
{
    public class ArticleModel : PageModel
    {
        [BindProperty]
        public AddComment NewComment { get; set; }
        
        public ArticleQueryModel Article { get; set; }
        public List<ArticleCategoryQueryModel> ArticleCategories { get; set; }
        public List<ArticleQueryModel> LatestArticles { get; set; }

        private readonly IArticleQuery _articleQuery;
        private readonly IArticleCategoryQuery _articleCategoryQuery;
        private readonly ICommentApplication _commentApplication;

        public ArticleModel(IArticleQuery articleQuery, IArticleCategoryQuery articleCategoryQuery, ICommentApplication commentApplication)
        {
            _articleQuery = articleQuery;
            _articleCategoryQuery = articleCategoryQuery;
            _commentApplication = commentApplication;
        }

        public void OnGet(string id)
        {
            Article = _articleQuery.GetArticleDetails(id);
            ArticleCategories = _articleCategoryQuery.GetArticleCategoryNames();
            LatestArticles = _articleQuery.GetLatestArticles();
        }

        public IActionResult OnPost(AddComment newComment, string articleSlug)
        {
            if (ModelState.IsValid)
            {
                newComment.Type = CommentType.Article;
                var result = _commentApplication.Add(newComment);
            }
            return RedirectToPage("/Article", new { id = articleSlug });
        }
    }
}

ServiceHost/Pages/ArticleCategory.cshtml.cs
using _01_LampshadeQuery.Contracts.Article;
using _01_LampshadeQuery.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Pages
{
    public class ArticleCategoryModel : PageModel
    {
        public ArticleCategoryQueryModel ArticleCategory { get; set; }
        public List<ArticleCategoryQueryModel> ArticleCategories { get; set; }
        public List<ArticleQueryModel> LatestArticles { get; set; }

        private readonly IArticleCategoryQuery _articleCategoryQuery;
        private readonly IArticleQuery _articleQuery;

        public ArticleCategoryModel(IArticleCategoryQuery articleCategoryQuery, IArticleQuery articleQuery)
        {
            _articleCategoryQuery = articleCategoryQuery;
            _articleQuery = articleQuery;
        }

        public void OnGet(string id)
        {
            ArticleCategory = _articleCategoryQuery.GetArticleCategoryDetails(id);
            ArticleCategories = _articleCategoryQuery.GetArticleCategoryNames();
            LatestArticles = _articleQuery.GetLatestArticles();
        }
    }
}

ServiceHost/ViewComponents/LatestArrivalsViewComponent.cs
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArrivalsViewComponent : ViewComponent
    {
        private readonly IProductQuery _productQuery;

        public LatestArrivalsViewComponent(IProductQuery productQuery)
        {
            _productQuery = productQuery;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productQuery.GetLatestArrivals();
            return View(products);
        }
    }
}

ServiceHost/ViewComponents/LatestArticlesViewComponent.cs
using _01_LampshadeQuery.Contracts.Article;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        private readonly IArticleQuery _articleQuery;

        public LatestArticlesViewComponent(IArticleQuery articleQuery)
        {
            _articleQuery = articleQuery;
        }

        public IViewComponentResult Invoke()
        {
            var articles = _articleQuery.GetLatestArticles();
            return View(articles);
        }
    }
}

ServiceHost/ViewComponents/ProductCategoryViewComponent.cs
using _01_LampshadeQuery.Contracts.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class ProductCategoryViewComponent:ViewComponent
    {
        private readonly IProductCategoryQuery _productCategoryQuery;

        public ProductCategoryViewComponent(IProductCategoryQuery productCategoryQuery)
        {
            _productCategoryQuery = productCategoryQuery;
        }

        public IViewComponentResult Invoke()
        {
            var productCategories = _productCategoryQuery.GetProductCategories();
            return View(productCategories);
        }
    }
}

ServiceHost/ViewComponents/SlideViewComponent.cs
using _01_LampshadeQuery.Contracts.Slide;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class SlideViewComponent : ViewComponent
    {
        private readonly ISlideQuery _slideQuery;

        public SlideViewComponent(ISlideQuery slideQuery)
        {
            _slideQuery = slideQuery;
        }

        public IViewComponentResult Invoke()
        {
            var slides = _slideQuery.GetSlides();
            return View(slides);
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
}


<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row justify-content-md-center">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6 text-center">
                                <br />
                                <h1 class="text-danger"><strong>403</strong></h1>
                                <br />
                                <h2><strong>دسترسی غیرمجاز!</strong></h2>
                                <br />
                                <h4>متاسفانه، شما اجازه دسترسی به این صفحه را ندارید!</h4>
                                <br />
                                <a class="btn btn-primary" asp-page="/Index">صفحه اصلی</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "صفحه اصلی";
}

@await Component.InvokeAsync("Slide")

@await Component.InvokeAsync("ProductCategory") 

@await Component.InvokeAsync("ProductCategoryWithProducts") 

@await Component.InvokeAsync("LatestArrivals")

<!--====================  banner hover area ====================-->
<div class="banner-hover-area section-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  banner hover wrapper  =======-->
                <div class="banner-hover-wrapper">
                    <div class="row">
                        <div class="col-md-6">
                            <!--=======  single hover banner  =======-->
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img1-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Black Friday</h4>
                                        <h3 class="big-text">Save Up To 50% Off</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                            <!--=======  End of single hover banner  =======-->
                        </div>

                        <div class="col-md-6">
                            <!--=======  single hover banner  =======-->
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img2-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Best Selling !</h4>
                                        <h3 class="big-text">Living Room Up To 70% Off</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                            <!--=======  End of single hover banner  =======-->
                        </div>
                    </div>
                </div>
                <!--=======  End of banner hover wrapper  =======-->
            </div>
        </div>
    </div>
</div>
<!--====================  End of banner hover area  ====================-->
<!--====================  feature logo area ====================-->
<div class="feature-logo-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  feature logo wrapper  =======-->
                <div class="feature-logo-wrapper section-space--inner-bottom">
                    <div class="row">
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/free_shipping.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">FREE SHIPPING WORLDWIDE</h4>
                                    <p class="short-desc">
                                        We offer free shipping via Standard Shipping on orders
                                        over $200.00
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/money_back.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">MONEY BACK GUARANTEE</h4>
                                    <p class="short-desc">
                                        If you're not satisfied with our product, we'll refund the
                                        purchase price*.
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/support247.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">ONLINE SUPPORT 24/7</h4>
                                    <p class="short-desc">
                                        Our friendly support team is available to help you 24
                                        hours a day, seven days a week
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                    </div>
                </div>
                <!--=======  End of feature logo wrapper  =======-->
            </div>
        </div>
    </div>
</div>
<!--====================  End of feature logo area  ====================-->

@await Component.InvokeAsync("LatestArticles")

<!--====================  newsletter area ====================-->
<div class="newsletter-area section-space--inner">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 offset-lg-2">
                <div class="newsletter-wrapper">
                    <p class="small-text">Special Ofers For Subscribers</p>
                    <h3 class="title">Ten Percent Member Discount</h3>
                    <p class="short-desc">
                        Subscribe to our newsletters now and stay up to date with new collections,
                        the latest lookbooks and exclusive offers.
                    </p>

                    <div class="newsletter-form">
                        <form id="mc-form" class="mc-form">
                            <input type="email" placeholder="Enter Your Email Address Here..." required>
                            <button type="submit" value="submit">SUBSCRIBE</button>
                        </form>

                    </div>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!--====================  End of newsletter area  ====================-->

ServiceHost/Pages/Login.cshtml
@page
@model ServiceHost.Pages.LoginModel
@{
    ViewData["Title"] = "ورود به سایت";
}


<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود به سایت</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود به سایت</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row justify-content-md-center">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                @if (!string.IsNullOrWhiteSpace(Model.LoginMessage))
                                {
                                    <div class="alert alert-danger text-center">
                                        @Model.LoginMessage
                                    </div>
                                }
                                <form method="post">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود به سایت</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label asp-for="LoginUser.UserName"></label>
                                                <input class="form-control" asp-for="LoginUser.UserName">
                                                <span class="text-danger" asp-validation-for="LoginUser.UserName"></span>
                                            </div>
                                            <div class="col-12">
                                                <label asp-for="LoginUser.Password"></label>
                                                <input class="form-control" asp-for="LoginUser.Password">
                                                <span class="text-danger" asp-validation-for="LoginUser.Password"></span>
                                            </div>
                                            @*<div class="col-sm-6">

                                                    <div class="check-box d-inline-block ml-0 ml-md-2 pull-right">
                                                        <input type="checkbox" id="remember_me">
                                                        <label for="remember_me">مرا به خاطر بسپار</label>
                                                    </div>

                                                </div>*@

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <span><i class="fa fa-lock"></i></span><a href="#" class="forget-pass-link"> رمز عبور را فراموش کرده اید؟</a>
                                            </div>
                                            <div class="col-sm-6 text-left text-sm-right">
                                                <span><i class="fa fa-user-plus"></i></span><a asp-page="/Register" class="forget-pass-link"> ثبت نام در سایت</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>