ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using AccountManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }

        public List<AccountViewModel> Accounts { get; set; }
        public AccountSearchModel SearchModel { get; set; }
        public SelectList Roles { get; set; }

        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }


        [NeedsPermissionAttribute(AccountPermissions.ListAccounts)]
        public void OnGet(AccountSearchModel searchModel)
        {
            Accounts = _accountApplication.Search(searchModel);
            Roles = new SelectList(_roleApplication.GetRolesList(), "Id", "Title");
        }


        public IActionResult OnGetCreate()
        {
            var command = new RegisterAccount
            {
                Roles = _roleApplication.GetRolesList()
            };
            return Partial("Create", command);
        }

        [NeedsPermission(AccountPermissions.CreateAccount)]
        public IActionResult OnPostCreate(RegisterAccount command)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("./Index");
            }
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }


        public IActionResult OnGetEdit(long id)
        {
            var command = _accountApplication.GetDetails(id);
            command.Roles = _roleApplication.GetRolesList();
            return Partial("Edit", command);
        }

        [NeedsPermission(AccountPermissions.EditAccount)]
        public IActionResult OnPostEdit(EditAccount command)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("./Index");
            }

            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword
            {
                Id = id
            };
            return Partial("ChangePassword", command);
        }

        [NeedsPermission(AccountPermissions.ChangePassword)]
        public IActionResult OnPostChangePassword(ChangePassword command)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("./Index");
            }

            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }

        [NeedsPermission(AccountPermissions.RemoveAccount)]
        public IActionResult OnGetRemove(long id)
        {
            var result = _accountApplication.Remove(id);
            return RedirectToPage("./Index");
        }

        [NeedsPermission(AccountPermissions.RestoreAccount)]
        public IActionResult OnGetRestore(long id)
        {
            var result = _accountApplication.Restore(id);
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public CreateRole NewRole { get; set; }

        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            NewRole = new CreateRole();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
                return Page();

            var result = _roleApplication.Create(NewRole);
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public EditRole Command { get; set; }

        public List<SelectListItem> Permissions = new List<SelectListItem>();

        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;


        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);

            //////////
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var dictionary in exposedPermissions)
                {
                    var groupName = dictionary.Key;

                    foreach (var permission in dictionary.Value)
                    {
                        var item = new SelectListItem
                        {
                            Group = new SelectListGroup
                            {
                                Name = groupName
                            },
                            Text = permission.Name,
                            Value = permission.Code.ToString(),
                            Selected = Command.Permissions.Any(code => code == permission.Code)
                        };
                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
                return Page();

            var result = _roleApplication.Edit(Command);
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        
        public List<RoleViewModel> Roles { get; set; }

        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            Roles = _roleApplication.GetRolesList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateRole();
            return Partial("Create", command);
        }

        public IActionResult OnPostCreate(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var command = _roleApplication.GetDetails(id);
            return Partial("Edit", command);
        }

        public IActionResult OnPostEdit(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }


        [BindProperty]
        public CreateArticle Article { get; set; }
        public SelectList ArticleCategories
        {
            get 
            {
                return new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
            }
        }

        public void OnGet()
        {
            Article = new CreateArticle();
            //ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle article)
        {
            if (ModelState.IsValid)
            {
                var result = _articleApplication.Create(article);
                return RedirectToPage("./Index");
            }
            return Page();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        [BindProperty]
        public EditArticle Article { get; set; }
        
        public SelectList ArticleCategories
        {
            get
            {
                return new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name");
            }
        }

        
        public void OnGet(long id)
        {
            Article = _articleApplication.GetDetails(id);
            //ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategoriesSelectList(), "Id", "Name", Article?.CategoryId);
        }

        public IActionResult OnPost(EditArticle article)
        {
            if (ModelState.IsValid)
            {
                var result = _articleApplication.Edit(article);
                return RedirectToPage("./Index");
            }
            return Page();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Account/ChangePassword.cshtml
@model AccountManagement.Application.Contracts.Account.ChangePassword
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تغییر رمز عبور کاربر</h4>
</div>

<form asp-page="./Index" asp-page-handler="ChangePassword"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="NewPassword" class="control-label"></label>
                    <input class="form-control" asp-for="NewPassword">
                    <span asp-validation-for="NewPassword" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RePassword" class="control-label"></label>
                    <input class="form-control" asp-for="RePassword">
                    <span asp-validation-for="RePassword" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ذخیره تغییرات</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Create.cshtml
@model AccountManagement.Application.Contracts.Account.RegisterAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد کاربر جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input class="form-control" asp-for="FullName">
                    <span asp-validation-for="FullName" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input class="form-control" asp-for="UserName">
                    <span asp-validation-for="UserName" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label"></label>
                    <input class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label"></label>
                    <select class="form-control" asp-for="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "Title")'>
                        <option value="0"> انتخاب نقش کاربر </option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RePassword" class="control-label"></label>
                    <input class="form-control" asp-for="RePassword">
                    <span asp-validation-for="RePassword" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label"></label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Edit.cshtml
@model AccountManagement.Application.Contracts.Account.EditAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش کاربر: @Model.FullName</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input class="form-control" asp-for="FullName">
                    <span asp-validation-for="FullName" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input class="form-control" asp-for="UserName">
                    <span asp-validation-for="UserName" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label"></label>
                    <input class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label"></label>
                    <select class="form-control" asp-for="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "Title")'>
                        <option value="0"> انتخاب نقش کاربر </option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label"></label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Accounts.Account.IndexModel
@using AccountManagement.Infrastructure.Configuration.Permissions
@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "| مدیریت کاربران";
}

<div class="row" permission="AccountPermissions.CreateAccount">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد کاربر جدید</a>
        </p>
    </div>
</div>

<div class="row" permission="AccountPermissions.SearchAccounts">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجوی کاربران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.FullName"></label>
                        <input class="form-control" asp-for="SearchModel.FullName" placeholder="نام">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.UserName"></label>
                        <input class="form-control" asp-for="SearchModel.UserName" placeholder="نام کاربری">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Mobile"></label>
                        <input class="form-control" asp-for="SearchModel.Mobile" placeholder="شماره موبایل">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.RoleId"></label>
                        <select class="form-control" asp-for="SearchModel.RoleId" asp-items="Model.Roles">
                            <option value="0"> انتخاب نقش </option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" permission="AccountPermissions.ListAccounts">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کاربران (@Model.Accounts.Count)</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام</th>
                                    <th>نام کاربری</th>
                                    <th>موبایل</th>
                                    <th>نقش کاربر</th>
                                    <th>تاریخ ثبت نام</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var account in Model.Accounts)
                                {
                                    <tr>
                                        <td>@account.Id</td>
                                        <td>
                                            <img src="~/UploadedFiles/@account.ProfilePhoto" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@account.FullName</td>
                                        <td>@account.UserName</td>
                                        <td>@account.Mobile</td>
                                        <td>@account.Role</td>
                                        <td>@account.CreationDate</td>
                                        <td>
                                            <a permission="AccountPermissions.EditAccount" class="btn btn-warning pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index","Edit", new {id=account.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            <a permission="AccountPermissions.ChangePassword" class="btn btn-primary pull-right m-rl-5"
                                               href="#showmodal=@Url.Page("./Index","ChangePassword", new {id=account.Id})">
                                                <i class="fa fa-key"></i> تغییر رمز عبور
                                            </a>
                                            @if (account.IsRemoved)
                                            {
                                                <a permission="AccountPermissions.RestoreAccount" class="btn btn-success pull-right m-rl-5"
                                                   asp-page="./Index" asp-page-handler="Restore" asp-route-id="@account.Id">
                                                    <i class="fa fa-check"></i> فعالسازی
                                                </a>
                                            }
                                            else
                                            {
                                                <a permission="AccountPermissions.RemoveAccount" class="btn btn-danger pull-right m-rl-5"
                                                   asp-page="./Index" asp-page-handler="Remove" asp-route-id="@account.Id">
                                                    <i class="fa fa-remove"></i> حذف
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}